### ISSUE TITLE
Update Eclipse BPMN plugin to work with current Eclipse version

### ISSUE THREAD

**Issue by eouthwaite** [adamfowleruk/scxmltocpf#102]
BPMN plugin works with Eclipse 4.4 (Luna), untested against 4.5 (Mars), definitely does not work with 4.6 (Neon).

As a workaround, the BPMN2 Modeler - Diagram Editor version 1.3.1.Final-v20161006-1425-B58 (id org.eclipse.bpmn2.modeler.feature.group) from Eclipse.org works, but has features that are not currently supported by workflow.

**Comment by eouthwaite** [comment]
Eclipse 4.7 - Oxygen - has been released.  Maybe this should be the target version.

**Comment by kghmanuel** [comment]
will prepare a PR for this

**Comment by eouthwaite** [comment]
will need to update https://github.com/marklogic-community/marklogicworkflow/blob/develop/documentation/DEV-MODELER.md documentation too

**Comment by luisjmart** [comment]
I was able to test the Modeler plugin with the latest version of Eclipse (oxygen 4.7.2)
