### ISSUE TITLE
Missing elements in JSON GET /v1/resources/process

### ISSUE THREAD

**Issue by eouthwaite** [adamfowleruk/scxmltocpf#120]
The auditTrail and metrics elements in the response from /v1/resources/process only contain the last element - see e2e-rest-process-xml vs e2e-rest-process-json on final test.

Will attempt to attach files for same request in both formats

**Comment by eouthwaite** [comment]
see gists [XML](https://gist.github.com/eouthwaite/27706b32188e9204e2903c8735dff03a) and [JSON](https://gist.github.com/eouthwaite/b010b8a7a4589eab01f422ade3acdb54)

**Comment by ken-tune** [comment]
Fixed
