### ISSUE TITLE
Create test for inclusive gateways

### ISSUE THREAD

**Issue by eouthwaite** [adamfowleruk/scxmltocpf#126]
It's documented here:
https://github.com/marklogic-community/marklogicworkflow/blob/develop/documentation/STEPS.md#inclusive-gateway

**Comment by eouthwaite** [comment]
#80 / #81 marked as complete - #81 has test (fork within fork) for loading BPMN - need test to follow workflow

**Comment by ken-tune** [comment]
First test created ( for an inclusive project with two branches, only one of which requires processing ). See feature-126.

TBD - test where we have two branches, *both* of which require processing.

**Comment by ken-tune** [comment]
Done
