### ISSUE TITLE
Document use of tools other than Eclipse plugin

### ISSUE THREAD

**Issue by damonfeldman** [adamfowleruk/scxmltocpf#127]
There is an eclipse plugin that provides the limited pallet of supported elements that our engine supports (though at this writing it only runs on an older version of Eclipse).

It is hopefully also possible to create BPMN flows in other tools using the appropriately-restricted elements. This process should be documented, and ideally tested on some other tool, particularly widely used, free tools.

**Comment by luisjmart** [comment]
I am testing this modeling tool Camunda.
    https://camunda.com/products/modeler/
