### ISSUE TITLE
Migrate deployment code to ml-gradle

### ISSUE THREAD

**Issue by damonfeldman** [adamfowleruk/scxmltocpf#129]
There is now a fairly mature migration path from Roxy to ml-gradle deployment.

See: https://github.com/marklogic-community/ml-gradle/wiki/Migrating-a-Roxy-project-to-ml-gradle .

Roxy tests can still be run, but may require support from the internal ML project to re-use Roxy tests from JUnit (see internal ML link: https://project.marklogic.com/repo/projects/INT/repos/roxy-test/browse )

**Comment by rjrudin** [comment]
@damonfeldman This is another candidate (just like the AM toolkit) for packaging up ML modules as a zip, publishing to a Maven repository, and automatically downloading and installing via ml-gradle.

**Comment by eouthwaite** [comment]
TODO: trim gradle.properties; update any readme files that involve deployment or unit tests

**Comment by eouthwaite** [comment]
Also TODO: Incorporate #90 as optional directory
