### ISSUE TITLE
Update Eclipse BPMN2 modeler palette for Sprint-002 deliverables

### ISSUE THREAD

**Issue by adamfowleruk** [adamfowleruk/scxmltocpf#31]
See other tasks developed/updated since

**Comment by eouthwaite** [comment]
Parallel and Inclusive Gateways are not included in the current palette

list should match documentation/STEPS.md #83

**Comment by luisjmart** [comment]
Parallel and Inclusive Gateways are present on the palette of the latest Modeler.
