### ISSUE TITLE
Errors when creating new MarkLogic Workflow Process File

### ISSUE THREAD

**Issue by peetkes** [adamfowleruk/scxmltocpf#64]
I installed the Development version of the MarkLogic workflow runtime environment and created a new process diagram. I did not install the BPMN2 Modeler. 
As soon as I click Finish on the Process Editor File I get the message "DocumentRoot id="unknown": Feature'packageName" not found.
Do I need to ignore that?
After fixing all red crosses in the diagram and saving it I can validate it without errors.
Am working with Eclipse Luna Service Release 1 (4.4.1)

**Comment by adamfowleruk** [comment]
Were you creating a CPF Process Diagram or MarkLogic Workflow Process Diagram, or another type of process diagram?
Have you tested using the Update Site rather than the development version (development version is NOT aimed at model developers, but at Eclipse plugin developers).

**Comment by peetkes** [comment]
I created a MarkLogic Workflow Process Diagram and I used the Update site for the development version.

**Comment by adamfowleruk** [comment]
Strange bug. The code that checked the packageName is commented out for the Workflow process diagram - so this message should not appear. (NewWorkflowProcessWizardPage1.java: 267-271)

Recommend a rebuild of the plugin for DEVELOP and patch for MASTER.

I can confirm the error message can be safely ignored - it will not affect the execution of uploaded process model diagrams in MarkLogic Workflow.

**Comment by adamfowleruk** [comment]
It would appear many of the sample BPMN2 files I created originally report an error to do with 'process ID not valid' - I have fixed this in the develop branch whilst fixing issue #67.

You should be able to test creating a new process file (or manually editing the process element's ID AND the second place in this file that relates to this ID (in the BPMN model display section) ).

Please let me know if this allows you to save your files. It works on my machine now.

**Comment by adamfowleruk** [comment]
I believe this is fixed in the DEVELOP url for the Eclipse plugin. Please test and confirm. 
https://raw.githubusercontent.com/adamfowleruk/marklogicworkflow/develop/eclipse/MarkLogicWorkflowUpdateSite/
