### ISSUE TITLE
Dynamic "assignee" allocation on a user task

### ISSUE THREAD

**Issue by steliann** [adamfowleruk/scxmltocpf#67]
The bpmn designer allows us to set a role/queue for a user task and we are able as well to retrieve all the workflow instances which are waiting for execution for a specific role/queue.
What we need is that a user task can be assigned to a named user and as well be able to move it back to the "queue" when this named user is not able to finish the task. 
What we think is important is that the process does not move to the next bpmn task during this assignment operation (I expect to be able to keep it under same user task if the call is made without rs:complete=true)
Also the process inbox service should be able to retrieve all process instances assigned to a specified user.

**Comment by adamfowleruk** [comment]
Queue's and Users are very, very different things. Easiest way to accomplish this is with two BPMN2 User Tasks - one for the queue, another for a dynamically assigned user. (Perhaps selected in the Queue step in the 'new assignee' dropdown before clicking on the 'reassign' action - just an idea). 

The variable containing the new username could be referenced inside a BPMN2 humanPerformer formal expression using $wf:process/wf:data/newAssignee/text() XPath.

Modifications to modules/workflowengine/actions/userTask.xqy will be needed to check for the dynamic humanPerformer expression.

Modifications to modules/app/models/workflow-import.xqy will be needed to copy over this assignee expression to the user task action CPF definition in the pipeline during import.

**Comment by adamfowleruk** [comment]
Fixed in current feature-67 branch. Example workflow in data/examples/051-restapi-test.bpmn - User Task 4 (Dynamic user assignment, top right of diagram).
