### ISSUE TITLE
Update data and attachments node on an updateRequest not implemented

### ISSUE THREAD

**Issue by steliann** [adamfowleruk/scxmltocpf#69]
The POST operation in the process service should be update like this (adding the root element):
let $feedback := wfa:complete-userTask($pid,$input/ext:updateRequest/wf:data/node(),$input/ext:updateRequest/wf:attachments/node())

Also, the workflow-actions.xqy "update-generic" function should have this:

  return (
    xdmp:node-replace(fn:doc(wfu:getProcessUri($processId))/wf:process/wf:data, wf:data{$data}/wf:data),
    xdmp:node-replace(fn:doc(wfu:getProcessUri($processId))/wf:process/wf:attachments, wf:attachments{$attachments}/wf:attachments)
  )

**Comment by adamfowleruk** [comment]
Please do your own fork of the repository, log an issue (with the reason why it is an issue), then create a branch for this feature as per CONTRIBUTING.md, and check the feature in. Then submit a pull request for your feature branch to the develop branch, referencing this issue (E.g. Fix #69 in comments).
