### ISSUE TITLE
Case: Create case management approach with ML Workflow

### ISSUE THREAD

**Issue by adamfowleruk** [adamfowleruk/scxmltocpf#90]
Data model using envelope pattern.
Determine how many processes can handle a case.
Determine how case fields related to process fields.
Determine how we handle common use cases, like case relating to a person or persons.
Determine how to hold links to other systems about these cases. 
Allow setting the fact that this case is a reopening of one or more prior cases.
Determine how to handle merge and split operations.
Do case documents themselves follow a finite state automata determined by CPF?

**Comment by adamfowleruk** [comment]
Brought forward for NL-K

**Comment by eouthwaite** [comment]
spec used on [swaggerhub](https://app.swaggerhub.com/apis/eouthwaite/case-management-api/1.0.1)

**Comment by eouthwaite** [comment]
add as optional folder structure now that #129 has completed
